# Generated by Django 5.1.7 on 2025-04-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0004_biblestudy_outreach_youth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
