# Generated by Django 5.1.7 on 2025-04-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0006_outreach_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='author',
            field=models.CharField(default='Unknown Author', max_length=100),
        ),
        migrations.AddField(
            model_name='biblestudy',
            name='leader',
            field=models.CharField(default='Unknown Leader', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='pastor',
            field=models.CharField(default='Unknown Pastor', max_length=100),
        ),
        migrations.AddField(
            model_name='schedule',
            name='pastor',
            field=models.CharField(default='Unknown Pastor', max_length=100),
        ),
        migrations.AddField(
            model_name='youth',
            name='leader',
            field=models.CharField(default='Unknown Leader', max_length=100),
        ),
    ]
