# Generated by Django 5.1.7 on 2025-04-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0007_announcement_author_biblestudy_leader_event_pastor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.CharField(default='00:00', max_length=200),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time',
            field=models.CharField(default='00:00', max_length=200),
        ),
    ]
