# Generated by Django 5.1.7 on 2025-04-07 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0008_alter_event_time_alter_schedule_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='event',
            new_name='title',
        ),
    ]
